# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-content:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
           fetch-depth: 2

      # Runs a single command using the runners shell
      - name: Run test Script
        run: sh test.sh
          
  test-commits:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: PR Commits Count
        id: commit_count
        uses: sultansoy/pr-commits-count@v1.0
   
      - if: ${{ steps.commit_count.outputs != 1 }}
        run: echo "Number of commits not equal to 1" && exit 1

